### ISSUE TITLE
Infografía Hilos

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/infografia-de-hilos-JazminloRI#2]
[Infografia_3.pdf.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-JazminloRI/files/6474343/Infografia_3.pdf.pdf)

**Comment by Eva155** [comment]
CALIFICACIÓN: 20 PUNTOS
CALIFICÓ: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
